language: php
php:
  - '7.2'
  - '7.3'

before_script:
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
